### ISSUE TITLE
index out of range with no middle name

### ISSUE THREAD

**Issue by somekid6** [NoahGWood/OpenEFT#25]
If a user has no middle name they get an index out of range error on submission.

![image](https://github.com/NoahGWood/OpenEFT/assets/53590807/04920643-f73d-4cb4-a0d9-a10b28774f37)

`
Traceback (most recent call last):
  File "/home/kasse/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/kasse/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kasse/OpenEFT/conversion/views.py", line 61, in step2
    fname = generate_eft(data)
  File "/home/kasse/OpenEFT/conversion/core/core.py", line 43, in generate_eft
    t2.name = "{}, {} {}".format(t2.lname, t2.fname, t2.mname[0])

Exception Type: IndexError at /new/step2
Exception Value: string index out of range
`

**Comment by NoahGWood** [comment]
This issue is related to OpenEFT v1 (Python/Docker implementation).

OpenEFT v2 is a complete rewrite with a native desktop architecture and no longer uses this workflow.

If this issue still occurs in v2, please open a new issue with details.
