### ISSUE TITLE
ungoogled chromium appimage fails to open in Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by somekid6** [NoahGWood/OpenEFT#28]
Issue:

openeft.py tries to open chrome.AppImage and fails as permission is denied.

	RUNNING BROWSER
	/bin/sh: 1: ./browser/linux/chrome.AppImage: Permission denied
	Exception in thread Thread-1 (browser):
	Traceback (most recent call last):
	  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
	    self.run()
	  File "/usr/lib/python3.10/threading.py", line 953, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/kasse/OpenEFT/openeft.py", line 31, in browser
	    if check_output("./browser/linux/chrome.AppImage --app=http://localhost:7100/", shell=True) is not None:
	  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
	    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
	  File "/usr/lib/python3.10/subprocess.py", line 524, in run
	    raise CalledProcessError(retcode, process.args,
	subprocess.CalledProcessError: Command './browser/linux/chrome.AppImage --app=http://localhost:7100/' returned non-zero exit status 126.

Solution for Ubuntu (does not work in WSL):

This can be fixed by changing the permissions of the AppImage file to allow execution as a program with

	chmod +x chrome.AppImage

I've verified changing this in build_linux.sh after the file is renamed solves this issue.

**Comment by NoahGWood** [comment]
This issue is related to OpenEFT v1 (Python/Docker implementation).

OpenEFT v2 is a complete rewrite with a native desktop architecture and no longer uses this workflow.

If this issue still occurs in v2, please open a new issue with details.
