### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by Bongi11** [NoahGWood/OpenEFT#33]
ImportError: libGL.so.1: cannot open shared object file: No such file or directory                                                                                                                                OpenEFT build complete. Update your /home/dan/.local/bin:/home/dan/OpenEFT/nbis/nfiq/bin:/home/dan/OpenEFT/nbis/nfseg/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu_2204.2.33.0_x64__79rhkp1fndgsc:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Device Service Thales Runtime and Drivers/bin:/mnt/c/Users/Owner/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Owner/.dotnet/tools:/snap/bin by typing 'source ~/.bashrc' and run the app by typing 'python3 openeft.py'       

this error try to run program
ImportError: libGL.so.1: cannot open shared object file: No such file or directory                                                                                                                                RUNNING BROWSER                                                                                                                                                                                                   /bin/sh: 1: ./browser/linux/chrome.AppImage: not found                                                                                                                                                            Exception in thread Thread-1 (browser):                                                                                                                                                                           Traceback (most recent call last):                                                                                                                                                                                  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner                                                                                                                                             self.run()                                                                                                                                                                                                      File "/usr/lib/python3.10/threading.py", line 953, in run                                                                                                                                                           self._target(*self._args, **self._kwargs)                                                                                                                                                                       File "/home/dan/OpenEFT/openeft.py", line 31, in browser                                                                                                                                                            if check_output("./browser/linux/chrome.AppImage --app=http://localhost:7100/", shell=True) is not None:                                                                                                        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output                                                                                                                                                 return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                                                                File "/usr/lib/python3.10/subprocess.py", line 524, in run                                                                                                                                                          raise CalledProcessError(retcode, process.args,                                                                                                                                                               subprocess.CalledProcessError: Command './browser/linux/chrome.AppImage --app=http://localhost:7100/' returned non-zero exit status 127.                                                                          dan@DESKTOP-K671AFJ:~/OpenEFT$

**Comment by somekid6** [comment]
I've recreated the issue and found the solution.

Try this:

Type 

	sudo apt install libgl1-mesa-glx

and press enter. 

Then run ./build_windows.sh again like in the guide. If that works for your machine let me know and I'll update the WSL guide.

**Comment by Bongi11** [comment]
That worked perfect thanks.
Can i email you directly about this program?

**Comment by NoahGWood** [comment]
This issue is related to OpenEFT v1 (Python/Docker implementation).

OpenEFT v2 is a complete rewrite with a native desktop architecture and no longer uses this workflow.

If this issue still occurs in v2, please open a new issue with details.
