### ISSUE TITLE
Error at submission: nfseg 13 1 1 1 0 /tmp/tmph97rppoq/R_FOUR.jp2' returned non-zero exit status 127

### ISSUE THREAD

**Issue by gmccolgan3** [NoahGWood/OpenEFT#34]
Get all the way to the submission and get an error.  It looks like I don't have the command "nfseg" installed.
I get the following error:

CalledProcessError at /new/step2
Command 'nfseg 13 1 1 1 0 /tmp/tmph97rppoq/R_FOUR.jp2' returned non-zero exit status 127.

with the following traceback:

Environment:

Request Method: POST
Request URL: http://localhost:7100/new/step2

Django Version: 4.1.7
Python Version: 3.10.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'conversion',
 'about',
 'viewer']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/home/gm3/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/gm3/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gm3/OpenEFT/conversion/views.py", line 61, in step2
    fname = generate_eft(data)
  File "/home/gm3/OpenEFT/conversion/core/core.py", line 54, in generate_eft
    each.convert()
  File "/home/gm3/OpenEFT/conversion/core/fingerprint.py", line 155, in convert
    self.segment()
  File "/home/gm3/OpenEFT/conversion/core/fingerprint.py", line 124, in segment
    a = check_output(x, shell=True, text=True).split('\n')
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,

Exception Type: CalledProcessError at /new/step2
Exception Value: Command 'nfseg 13 1 1 1 0 /tmp/tmph97rppoq/R_FOUR.jp2' returned non-zero exit status 127.

**Comment by BLACKCATS56** [comment]
I have the same issue. Did you ever figure it out?

**Comment by jbierling** [comment]
Same problem.

Anyone figure it out?

**Comment by NoahGWood** [comment]
This issue is related to OpenEFT v1 (Python/Docker implementation).

OpenEFT v2 is a complete rewrite with a native desktop architecture and no longer uses this workflow.

If this issue still occurs in v2, please open a new issue with details.
