### ISSUE TITLE
nfseg Reports "image type UNKNOWN : not supported"

### ISSUE THREAD

**Issue by AnalyticETH** [NoahGWood/OpenEFT#36]
I got the program somewhat working by using the modified fork of NBIS that allows for use of a newer GCC version (https://github.com/OwenPemberton/nbis).

Now, however, after submitting all of the data in the application, when nfseg is called to process the split fingerprint photos, it fails saying it cannot recognize the image format of the .jp2 image. I have extracted a copy of the .jp2 image nfseg is trying to process and it is a valid grayscale .jp2 file/image.

Has anyone else seen this problem and does anyone have any ideas to resolve it? Thanks!

Django output:
```
Command 'nfseg 13 1 1 1 0 /tmp/tmpa3rzr_1c/R_FOUR.jp2' returned non-zero exit status 253.
Request Method: | POST
-- | --
http://127.0.0.1:7100/new/step2
4.1.7
CalledProcessError
Command 'nfseg 13 1 1 1 0 /tmp/tmpa3rzr_1c/R_FOUR.jp2' returned non-zero exit status 253.
/usr/lib/python3.10/subprocess.py, line 526, in run
conversion.views.step2
/usr/bin/python3
3.10.12
['/home/m/OpenEFT',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/usr/local/lib/python3.10/dist-packages',  '/usr/lib/python3/dist-packages']
```

Python output:
```
[INFO] tile number 1 / 1
[INFO] Generated outfile /tmp/tmpa3rzr_1c/R_FOUR.jp2
encode time: 1708 ms
ERROR : read_and_decode_grayscale_image : /tmp/tmpa3rzr_1c/R_FOUR.jp2 : image type UNKNOWN : not supported
Internal Server Error: /new/step2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m/OpenEFT/conversion/views.py", line 61, in step2
    fname = generate_eft(data)
  File "/home/m/OpenEFT/conversion/core/core.py", line 54, in generate_eft
    each.convert()
  File "/home/m/OpenEFT/conversion/core/fingerprint.py", line 155, in convert
    self.segment()
  File "/home/m/OpenEFT/conversion/core/fingerprint.py", line 124, in segment
    a = check_output(x, shell=True, text=True).split('\n')
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'nfseg 13 1 1 1 0 /tmp/tmpa3rzr_1c/R_FOUR.jp2' returned non-zero exit status 253.
```

System is a fresh install of Ubuntu Jammy LTS running on an Intel machine.

**Comment by AnalyticETH** [comment]
Followed the guide here and it worked: https://github.com/NoahGWood/OpenEFT/discussions/26
